---

- name: Update Arch cache
  community.general.pacman:
    update_cache: yes
  when: ansible_facts['distribution'] == "Archlinux"

- name: Update Ubuntu cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 600
  when: ansible_facts['distribution'] == "Ubuntu"
