---

- name: Update apt cache
  ansible.builtin.include_tasks: tasks/update_package_cache.yaml

- name: Upgrade all packages
  ansible.builtin.include_tasks: tasks/upgrade_packages.yaml

- name: Install packages
  ansible.builtin.import_tasks: tasks/packages.yaml
