---

name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    name: Lint bureau

    defaults:
      run:
        working-directory: bureau

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Lint Ansible
        run: ansible-lint
